### PR TITLE
fix(vscode): Add useMemo to avoid infinite loop in identity selector

### LINKED ISSUE #5987: Minified React error #185 when clicking on an Azure Monitor Logs action inside VS Code
### Describe the Bug with repro steps 

1. Open up Developer Tools within VS Code 
2. Right click on `workflow.json` to open up a menu. 
3. Select 'Open Designer' 
4. Click on Azure Monitor Logs action 

After clicking on the action, the designer window goes blank (white screen of death). The following error is displayed then appears in the console:

> Error: Minified React error #185; visit [https://reactjs.org/docs/error-decoder.html?invariant=185](<https://reactjs.org/docs/error-decoder.html?invariant=185>) for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

### What type of Logic App Is this happening in? 

Standard (VSCode)

### Which operating system are you using? 

MacOS

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

```json
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {
            "Initialize_now_datetime": {
                "type": "InitializeVariable",
                "inputs": {
                    "variables": [
                        {
                            "name": "nowDateTime",
                            "type": "string",
                            "value": "@convertFromUtc(utcNow(), 'Eastern Standard Time', 'U')"
                        }
                    ]
                },
                "runAfter": {
                    "Initialize_number_of_errors_and_warnings": [
                        "SUCCEEDED"
                    ]
                }
            },
            "Initialize_number_of_errors_and_warnings": {
                "type": "InitializeVariable",
                "inputs": {
                    "variables": [
                        {
                            "name": "numErrorsWarnings",
                            "type": "integer",
                            "value": 0
                        }
                    ]
                },
                "runAfter": {}
            },
            "Query_logs_for_errors_and_warning_messages": {
                "type": "ApiConnection",
                "inputs": {
                    "host": {
                        "connection": {
                            "referenceName": "azuremonitorlogs-1"
                        }
                    },
                    "method": "post",
                    "body": "traces\n| project timestamp_est=format_datetime(datetime_utc_to_local(timestamp, 'US/Eastern'), 'yyyy-MM-dd hh:mm tt'),\n    timestamp,\n    functionApp=cloud_RoleName,\n    functionName=operation_Name,\n    epic_instance = extract('Epic Instance: (.+)', 1, message),\n    message,\n    severity=severityLevel\n| where 'func-ixo3gu2irrsks' has functionApp\n    and timestamp >= ago(5m)\n    and severity >= 2\n    and (isnotempty(functionName) or message has \"No job functions found.\")\n| project-away timestamp\n| order by timestamp_est desc",
                    "path": "/queryData",
                    "queries": {
                        "subscriptions": "@parameters('subscriptionId')",
                        "resourcegroups": "@parameters('resourceGroupName')",
                        "resourcetype": "Application Insights",
                        "resourcename": "@parameters('appInsightsName')",
                        "timerange": "Set in query"
                    }
                },
                "runAfter": {
                    "Initialize_now_datetime": [
                        "SUCCEEDED"
                    ]
                }
            }
        },
        "contentVersion": "1.0.0.0",
        "outputs": {},
        "triggers": {
            "Check_every_5_minutes": {
                "type": "Recurrence",
                "recurrence": {
                    "interval": 5,
                    "frequency": "Minute",
                    "timeZone": "Eastern Standard Time"
                }
            }
        }
    },
    "kind": "Stateful"
}
```

### Screenshots or Videos

Image

### Browser

n/a

### Additional context

*No response*

### PR DESCRIPTION
**Pull request by ccastrotrejo**
This pull request includes several optimizations to the `IdentitySelector` component in the `identityselector.tsx` file. The primary changes involve the addition of the `useMemo` hook and reordering dependencies for the `useEffect` hook to improve performance and maintainability.

Performance improvements:

* Added `useMemo` to memoize the `identity` value, preventing unnecessary recalculations.
* Included `useMemo` import to support the memoization of `identity`.

Fixes #5987

### CODE REVIEW

**Review by hartra344 — APPROVED** [review]

File: libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/parametersTab/identityselector.tsx [hunk 1]
```diff
@@ -54,14 +54,22 @@ export const IdentitySelector = (props: IdentitySelectorProps) => {
...
 
+  const isIdentityInLogicApp = useMemo(() => {
+    return isIdentityPresentInLogicApp(selectedKey, identity);
+  }, [identity, selectedKey]);
+
+  const isIdentityWithLogicApp = useMemo(() => {
+    return isIdentityAssociatedWithLogicApp(identity);
+  }, [identity]);
+
   useEffect(() => {
```
Comment (rllyy97) [inline libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/parametersTab/identityselector.tsx:65]: It looks like `identity` not being memoized was the issue here (causing it to run on every render)
If that's true shouldn't we be memoizing `identity` on line 45?
Otherwise this still runs into the same issue

**Review by rllyy97 — CHANGES_REQUESTED** [review]

File: libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/parametersTab/identityselector.tsx (hunk 1 above)
Comment (ccastrotrejo) [reply libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/parametersTab/identityselector.tsx]: Thank you so much, made the fix and it worked

**Review by rllyy97 — APPROVED** [review]
