### PR TITLE
fix(designer): Updated and enabled multiple built-in triggers for Consumption

### LINKED ISSUE #2000: Consumption _Trigger : Missing other trigger options while filtering with In-app
### Describe the Bug with repro steps

1.Create a Logic app in consumption.
2.Open the logic app in new preview designer.
3.While selecting the trigger and applying the in app filter ,More the trigger options should present in it.

**Expected :**  While selecting the trigger and applying the in app filter ,More the trigger options should present in it.

**Actual :** While selecting the trigger and applying the in app filter ,only request trigger option is present in it

### Workflow JSON

```json
{
  "definition": {
    "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
    "actions": {},
    "contentVersion": "1.0.0.0",
    "outputs": {},
    "triggers": {}
  },
  "connectionReferences": {},
  "parameters": {}
}
```

### Screenshots or Videos

image

### Browser

Edge

### Additional context

**Environmental Details:**

**URL:** [https://aka.ms/emastaging-flowstip1](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Femastaging-flowstip1&data=05%7C01%7Cv-govubilish%40microsoft.com%7C5dc1b66779e54ebfb20b08db3bf92e3f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638169713681866036%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Ox8FGZYcViENAadUWbkyOt05VGv%2FAvR7SYpEG%2BGHVDI%3D&reserved=0)
**Version :** 2.30410.1.3

### PR DESCRIPTION
**Pull request by rllyy97**
## Main Changes
- Updated/Added/Enabled multiple built-in triggers for Consumption
  - APIM Trigger
  - App Service Trigger
  - HTTP / HTTP+Swagger / HTTP Webhook
  - Recurrence / Sliding Window
  - `// Batch not completed in this PR`

Portal-side changes are also in [THIS PR](https://msazure.visualstudio.com/One/_git/AzureUX-LogicAppsPortal/pullrequest/7953328)

Fixes #2000
  
image

### CODE REVIEW

**Review by Eric-B-Wu — APPROVED** [review]

File: libs/designer/src/lib/common/constants.ts [hunk 1]
```diff
@@ -909,11 +909,12 @@ export default {
...
   AZURE_RESOURCE_ACTION_TYPES: {
     SELECT_APIMANAGEMENT_ACTION: 'apimanagement',
-    SELECT_APIMANAGEMENT_TRIGGER: 'selectapimanagementtrigger',
+    SELECT_APIMANAGEMENT_TRIGGER: 'apimanagementtrigger',
     SELECT_APPSERVICE_ACTION: 'appservice',
-    SELECT_APPSERVICE_TRIGGER: 'selectappservicetrigger',
+    SELECT_APPSERVICE_TRIGGER: 'appservicetrigger',
     SELECT_FUNCTION_ACTION: 'azurefunction',
     SELECT_BATCH_WORKFLOW_ACTION: 'sendtobatch',
+    SELECT_BATCH_WORKFLOW_TRIGGER: 'sendtobatchtrigger',
```
Comment (preetriti1) [inline libs/designer/src/lib/common/constants.ts:917]: sendtobatch is an action, batch is the trigger

File: libs/services/designer-client-services/src/lib/base/operationmanifest.ts [hunk 2]
```diff
@@ -43,6 +43,7 @@ import { ArgumentException, equals, UnsupportedException } from '@microsoft/util
 import type { OperationInfo, OperationManifest } from '@microsoft/utils-logic-apps';
 
 const apimanagement = 'apimanagement';
+const apimanagementtrigger = 'apimanagementtrigger';
```
Comment (preetriti1) [inline libs/services/designer-client-services/src/lib/base/operationmanifest.ts:46]: Anything related to consumption like any trigger/action specific to consumption should be present in consumption service, sendtobatch is an actionType and not a triggertype.. , batch is the trigger type. Your changes below breaks the batch trigger in standard.

YOur changes in getOPerationInfo assumes sendtobatch as a operation type which is common for both trigger and action. Please do test out the changes and if its not complete please do not checkin
