### PR TITLE
fix(designer): Add description for Condition action

### LINKED ISSUE #3549: Many form fields do not have visible labels
### Describe the Bug with repro steps

1. Create a new flow with designer standalone (nx serve).
2. Add a Condition action.
3. Observe that some fields (notably, the condition fields) don't have visible labels.

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Workflow JSON

_No response_

### Screenshots or Videos

image

### Browser

Edge

### Additional context

Related internal bug: https://msazure.visualstudio.com/One/_workitems/edit/13400375

AB#25622117

### PR DESCRIPTION
**Pull request by Ram-G**
Fixes #3549 

- **Please check if the PR fulfills these requirements**

* [x] The commit message follows our guidelines
* [ ] Tests for the changes have been added (for bug fixes/features)
* [ ] Docs have been added / updated (for bug fixes / features)

- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- Bugfix

- **What is the current behavior?** (You can also link to an open issue here)
- Condition action contains several editor fields with no description making it difficult for accessible users to use.

- **What is the new behavior (if this is a feature change)?**
- A small description has been added specifically for the Condition action so accessible users will find it easier to use.

- **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No

- **Please Include Screenshots or Videos of the intended change**:
image

### CODE REVIEW

File: libs/designer-ui/src/lib/settings/settingsection/settingTokenField.tsx [hunk 1]
```diff
@@ -60,9 +61,20 @@ export interface SettingTokenFieldProps extends SettingProps {
 }
 
 export const SettingTokenField = ({ ...props }: SettingTokenFieldProps) => {
+  const intl = useIntl();
```
Comment (Eric-B-Wu) [inline libs/designer-ui/src/lib/settings/settingsection/settingTokenField.tsx:64]: will we want this to show in all cases including the simplequerybuilder or hybridquerybuilder?

Comment (Ram-G) [reply libs/designer-ui/src/lib/settings/settingsection/settingTokenField.tsx:64]: The intention is to show the description for all Condition actions.

Are simplequerybuilder and hybridquerybuilder also a type of Condition action? If so, can you share 
1) how they can be identified in code
2) how can I verify the UI for them?

Comment (Eric-B-Wu) [reply libs/designer-ui/src/lib/settings/settingsection/settingTokenField.tsx:64]: yes they are also of condition editor type, they are diffrentiated with editorOption: "isOldFormat" for simple query builder, and "isHybridEditor" for hybrid query builder. If you are doing this change in the settingtokenfield, it can be accessed with the editorViewModel.isOldFormat; however, if this is only wanted on the condition editor, then we can just move this description to the ui component where condition editor is hosted, and give it an optional prop to show that description: libs\designer-ui\src\lib\querybuilder\index.tsx

Comment (Ram-G) [reply libs/designer-ui/src/lib/settings/settingsection/settingTokenField.tsx]: Moved the description to querybuilder file.

**Review by Eric-B-Wu — APPROVED** [review]

File: libs/designer-ui/src/lib/querybuilder/index.tsx [hunk 2]
```diff
@@ -76,8 +86,21 @@ export const QueryBuilderEditor = ({ getTokenPicker, groupProps, readonly, onCha
     setRootProp(newProps);
   };
 
+  let description;
+  if (showDescription) {
```
Comment (Eric-B-Wu) [inline libs/designer-ui/src/lib/querybuilder/index.tsx:90]: nit: but because we're only rendering it on showDescription, we don't need to optionally set the description
