### PR TITLE
fix(designer): Do not show label for array editor in collapsed view

### LINKED ISSUE #4879: Label name remains same when switching to entire array input
### Describe the Bug with repro steps

1. Go to Portal and create a Logic App (Standard) workflow 
2. Add the Get chat completions operation or Vector Search operation 
3. for the parameters, notice that it says label "array item" and that remains same when you switch parameter to accept entire array input instead of items 

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Workflow JSON

_No response_

### Screenshots or Videos

https://github.com/Azure/LogicAppsUX/assets/80121421/fd3f21a7-f219-4f29-858f-2039daeecb8c

### Browser

Chrome

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by preetriti1**
- **Please check if the PR fulfills these requirements**

* [x] The commit message follows our guidelines
* [ ] Tests for the changes have been added (for bug fixes/features)
* [ ] Docs have been added / updated (for bug fixes / features)

- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Bug fix

- **What is the current behavior?** (You can also link to an open issue here)
fixes #4879 

- **What is the new behavior (if this is a feature change)?**
We will not show any label for array input in collapsed view

- **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No

- **Please Include Screenshots or Videos of the intended change**:
image

### CODE REVIEW

File: libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/formInputs/connectionMultiAuth.tsx [hunk 1]
```diff
@@ -11,12 +12,17 @@ export interface ConnectionMultiAuthInputProps {
 }
 
 const ConnectionMultiAuthInput = ({ isLoading, value, onChange, connectionParameterSets }: ConnectionMultiAuthInputProps) => {
+  const authType = useIntl().formatMessage({
```
Comment (hartra344) [inline libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/formInputs/connectionMultiAuth.tsx:15]:
```suggestion
  const intl = useIntl()
  const authType = intl.formatMessage({
```

Format-js linter is very dumb, in fact it's letting you use an ID that isn't correct at all. It always needs to be intl.formatMessage and the ID needs to be a hash of the input(the linter auto fix takes care of this)

**Review by hartra344 — CHANGES_REQUESTED** [review]

**Review by ccastrotrejo — APPROVED** [review]

**Review by hartra344 — APPROVED** [review]
