### PR TITLE
fix(designer):  Parse of xml inputs/outputs in monitoring view

### LINKED ISSUE #2727: Monitoring View does not parse base 64 inputs/outputs
### Describe the Bug with repro steps

In the previous version of the designer, the content envelope containing the base64 encoded version of the desired output was decoded and displayed in the output monitor for the designer, which is not the case anymore.

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Workflow JSON

_No response_

### Screenshots or Videos

Output received from API call: 

{
    "statusCode": "OK",
    "body": {
        "content": {
            "$content-type": "application/xml",
            "$content": "PENSRUFURVJlc3BvbnNlIHhtbG5zPSJodHRwOi8vTWljcm9zb2Z0LkxvYlNlcnZpY2VzLlNhcC8yMDA3LzAzL0JhcGkvQlVTMTAxMS8iPjxCQU5LQ09VTlRSWT48L0JBTktDT1VOVFJZPjxCQU5LS0VZPjwvQkFOS0tFWT48UkVUVVJOPjxUWVBFIHhtbG5zPSJodHRwOi8vTWljcm9zb2Z0LkxvYlNlcnZpY2VzLlNhcC8yMDA3LzAzL1R5cGVzL1JmYy8iPkU8L1RZUEU+PElEIHhtbG5zPSJodHRwOi8vTWljcm9zb2Z0LkxvYlNlcnZpY2VzLlNhcC8yMDA3LzAzL1R5cGVzL1JmYy8iPkFSPC9JRD48TlVNQkVSIHhtbG5zPSJodHRwOi8vTWljcm9zb2Z0LkxvYlNlcnZpY2VzLlNhcC8yMDA3LzAzL1R5cGVzL1JmYy8iPjEwNDwvTlVNQkVSPjxNRVNTQUdFIHhtbG5zPSJodHRwOi8vTWljcm9zb2Z0LkxvYlNlcnZpY2VzLlNhcC8yMDA3LzAzL1R5cGVzL1JmYy8iPkJhbmsgS2V5IGFhIG11c3QgY29udGFpbiBvbmx5IG51bWJlcnM8L01FU1NBR0U+PExPR19OTyB4bWxucz0iaHR0cDovL01pY3Jvc29mdC5Mb2JTZXJ2aWNlcy5TYXAvMjAwNy8wMy9UeXBlcy9SZmMvIj48L0xPR19OTz48TE9HX01TR19OTyB4bWxucz0iaHR0cDovL01pY3Jvc29mdC5Mb2JTZXJ2aWNlcy5TYXAvMjAwNy8wMy9UeXBlcy9SZmMvIj4wMDAwMDA8L0xPR19NU0dfTk8+PE1FU1NBR0VfVjEgeG1sbnM9Imh0dHA6Ly9NaWNyb3NvZnQuTG9iU2VydmljZXMuU2FwLzIwMDcvMDMvVHlwZXMvUmZjLyI+QmFuayBLZXk8L01FU1NBR0VfVjE+PE1FU1NBR0VfVjIgeG1sbnM9Imh0dHA6Ly9NaWNyb3NvZnQuTG9iU2VydmljZXMuU2FwLzIwMDcvMDMvVHlwZXMvUmZjLyI+YWE8L01FU1NBR0VfVjI+PE1FU1NBR0VfVjMgeG1sbnM9Imh0dHA6Ly9NaWNyb3NvZnQuTG9iU2VydmljZXMuU2FwLzIwMDcvMDMvVHlwZXMvUmZjLyI+PC9NRVNTQUdFX1YzPjxNRVNTQUdFX1Y0IHhtbG5zPSJodHRwOi8vTWljcm9zb2Z0LkxvYlNlcnZpY2VzLlNhcC8yMDA3LzAzL1R5cGVzL1JmYy8iPjwvTUVTU0FHRV9WND48UEFSQU1FVEVSIHhtbG5zPSJodHRwOi8vTWljcm9zb2Z0LkxvYlNlcnZpY2VzLlNhcC8yMDA3LzAzL1R5cGVzL1JmYy8iPjwvUEFSQU1FVEVSPjxST1cgeG1sbnM9Imh0dHA6Ly9NaWNyb3NvZnQuTG9iU2VydmljZXMuU2FwLzIwMDcvMDMvVHlwZXMvUmZjLyI+MDwvUk9XPjxGSUVMRCB4bWxucz0iaHR0cDovL01pY3Jvc29mdC5Mb2JTZXJ2aWNlcy5TYXAvMjAwNy8wMy9UeXBlcy9SZmMvIj48L0ZJRUxEPjxTWVNURU0geG1sbnM9Imh0dHA6Ly9NaWNyb3NvZnQuTG9iU2VydmljZXMuU2FwLzIwMDcvMDMvVHlwZXMvUmZjLyI+TE9HSUNBUFBTPC9TWVNURU0+PC9SRVRVUk4+PC9DUkVBVEVSZXNwb25zZT4="
        }
    }
}

Expected Behavior: 
MicrosoftTeams-image (9)

Actual Behaviour: 
MicrosoftTeams-image (10)

### Browser

Edge

### Additional context

_No response_

AB#24244819

### PR DESCRIPTION
**Pull request by ccastrotrejo**
- **Please check if the PR fulfills these requirements**

* [X] The commit message follows our guidelines
* [X] Tests for the changes have been added (for bug fixes/features)
* [ ] Docs have been added / updated (for bug fixes / features)

- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
When parsing the inputs/outputs, if the object has a content property will display the content property object instead of the whole object

- **What is the current behavior?** (You can also link to an open issue here)
Fix #2727 

- **What is the new behavior (if this is a feature change)?**

- **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

- **Please Include Screenshots or Videos of the intended change**:
#### Before
Screenshot 2023-06-20 at 12 42 55 PM

#### After
Screenshot 2023-06-20 at 12 41 12 PM

### CODE REVIEW

File: libs/services/designer-client-services/src/lib/standard/run.ts [hunk 1]
```diff
@@ -263,7 +263,7 @@ export class StandardRunService implements IRunService {
         : response;
 
     return Object.keys(dictionaryResponse).reduce((prev, current) => {
-      return { ...prev, [current]: { displayName: current, value: dictionaryResponse[current] } };
+      return { ...prev, [current]: { displayName: current, value: dictionaryResponse[current].content ?? dictionaryResponse[current] } };
```
Comment (preetriti1) [inline libs/services/designer-client-services/src/lib/standard/run.ts:266]: Is this null ref safe? What if dictionaryresponse[current] is undefined

Comment (ccastrotrejo) [reply libs/services/designer-client-services/src/lib/standard/run.ts:266]: `dictionaryresponse[current]` can't be undefined because `dictionaryResponse` its the object that gets iterated and `current` its the current key in the iteration. What can be undefined it's the `content` property but if that's the case will only return `dictionaryResponse[current]`

**Review by preetriti1 — APPROVED** [review]
