### PR TITLE
fix(vscode): improve extension bundle path parsing for multi-line command output

### LINKED ISSUE #8319: Functions looking for local settings in wrong place
### Severity

P1 - Critical (Blocking production)

### Describe the Bug with repro steps

Does this occur consistently? Yes

I am getting an error when trying to start the logic app designer.  The error has appeared after uninstalling and reinstalling VS Code.  I have also tried deleting the .azurelogicapps and .azure-functions-core-tools folders and letting them rebuild.

The issue seems to be around the location of my local.settings.json file.  When I start the designer "c:\users\<username>\.azurelogicapps\dependencies\FuncCoreTools\func GetExtensionBundlePath" runs and states that it has found local.settings.json (presumably in the project root folder where it exists) but then stating that it is in the app root rather than the project root (C:\Users\<username>\AppData\Local\Programs\Microsoft VS Code)

If I run the same command in my terminal I get
local.settings.json found in root directory (C:\Users\<username>\project_path\project_workspace\project).
Which is where the file is actually located.

Repro steps:

1.  Open the designer in a Logic App Standard project
2.  The following error is received.  It is as if it is looking for local.settings.json in the app root rather than the project root.

Action: azureLogicAppsStandard.openDesigner
Error type: ENOENT
Error message: ENOENT: no such file or directory, scandir 'C:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\local.settings.json found in root directory (C:\Users\<username>\AppData\Local\Programs\Microsoft VS Code).
C:\Users\<username>\.azure-functions-core-tools\Functions\ExtensionBundles\Microsoft.Azure.Functions.ExtensionBundle.Workflows'
Correlation Id: 89F5BDDA-9979-4165-86F7-A7B00BA4F023
Session id: e7d63754-63d2-421b-a102-245958b19a421759495942137
Extension version: 5.165.9
Extension bundle version: 1.138.54
OS: win32 (Windows_NT 10.0.26100)
OS arch: x64
Product: Visual Studio Code
Product version: 1.104.3
UTC time: Fri, 03 Oct 2025 12:55:35 GMT

<details>
<summary>Settings</summary>

```
{
  "dataMapperVersion": 2,
  "validateFuncCoreTools": true,
  "autoRuntimeDependenciesPath": "c:\\users\\<username>\\.azurelogicapps\\dependencies",
  "autoRuntimeDependenciesValidationAndInstallation": true,
  "parameterizeConnectionsInProjectLoad": false
}
```

</details>

### What type of Logic App Is this happening in?

Standard (VSCode)

### Are you experiencing a regression?

_No response_

### Which operating system are you using?

Windows

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Workflow JSON

```json

```

### Screenshots or Videos

_No response_

### Environment

VS Code 1.104.3
ms-azuretools.vscode-azurelogicapps 5.165.9
ms-azuretools.vscode-azurefunctions 1.19.1

zure Functions Core Tools
Core Tools Version:       4.3.0+df07acf9d837d635d1efc2c973225f4f1c8a4333 (64-bit)
Function Runtime Version: 4.1042.100.25374

Local binary .NET SDK version 8.0.414
1:52:43 PM: Azure Logic Apps Standard Runtime Dependencies validation and installation completed successfully.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ccastrotrejo**
## Commit Type
- [x] fix - Bug fix

## Risk Level
- [X] Medium - Moderate changes, some user impact

## What & Why
The `getExtensionBundleFolder()` function was failing to correctly parse the extension bundle path when the Azure Functions Core Tools command returned multi-line output. The previous implementation used `execSync` directly and expected a single-line response, but in practice, the command often returns additional informational messages before the actual path.

This PR refactors the path extraction logic to:
- Handle multi-line command output by splitting and filtering lines
- Detect Windows and Unix-style paths correctly
- Use improved regex matching to extract the ExtensionBundles folder path
- Add fallback parsing logic for edge cases
- Replace direct `child_process.execSync` call with the `executeCommand` utility for better consistency
- Add telemetry events for debugging path extraction failures

## Impact of Change
- **Users**: VS Code extension users will experience more reliable extension bundle path detection, reducing errors when running Logic Apps locally
- **Developers**: The code is now more maintainable with better error handling and clearer parsing logic
- **System**: No performance impact; improved reliability in path detection

## Test Plan
- [x] Unit tests added/updated
- [x] Manual testing completed
- [x] Tested in: Added comprehensive unit tests covering:
  - Multi-line output parsing (Windows and Unix paths)
  - Mixed line endings (\r\n, \n)
  - Paths with spaces and special characters
  - Error handling for malformed output
  - Fallback parsing logic
  - Edge cases with multiple ExtensionBundles mentions

## Contributors
@andrew-eldridge @wsilveiranz 

## Screenshots
CleanShot 2025-10-06 at 12 35 03@2x

Fixes #8319

### CODE REVIEW

File: apps/vs-code-designer/src/app/utils/bundleFeed.ts [hunk 1]
```diff
@@ -327,26 +327,54 @@ export async function getBundleVersionNumber(): Promise<string> {
...
+
+    // Split by newlines and find the line that contains the actual path
+    const lines = result
+      .split(/\r?\n/)
+      .map((line) => line.trim())
+      .filter((line) => line.length > 0);
+
+    // The path line should contain "ExtensionBundles" and look like a valid path
+    const pathLine = lines.find(
+      (line) => line.includes('ExtensionBundles') && (line.match(/^[A-Z]:\\/i) || line.startsWith('/')) // Windows or Unix path
```
Comment (andrew-eldridge) [inline apps/vs-code-designer/src/app/utils/bundleFeed.ts:346]: This all looks good- are we positive each of the regex cover all edge cases? Does it make sense to add a fallback to some sort of best-effort parsing in the case where this fails to find an exact match?

**Review by andrew-eldridge — APPROVED** [review]
