### PR TITLE
fix(Designer): Hide Unsupported Actions/Connectors for Standard

### LINKED ISSUE #5619: Hide Unsupported Actions/Connectors for Standard
### Describe the Bug with repro steps 

When seraching for actions, all actions including the ones that are not supported in standard shows. As a user, you will be able to pick this action and may get confused due to the errors since it will not work.

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

image

image

### Browser 

All

### Additional context 

*No response*

### PR DESCRIPTION
**Pull request by Elaina-Lee**
## Requirement Checklist

* [X] The commit message follows our guidelines
* [X] Tests for the changes have been added (for bug fixes or features)

## Type of Change

* [X] Bug fix
* [ ] Feature
* [ ] Other

* hides gmail connectors / api operations for standard
fixes #5619 

* [ ] **This is a breaking change.**

## Screenshots or Videos (if applicable)

https://github.com/user-attachments/assets/49a32c60-aa84-43fd-993f-c54d4e4b5a78

### CODE REVIEW

File: libs/logic-apps-shared/src/designer-client-services/lib/base/search.ts [hunk 1]
```diff
@@ -171,7 +178,8 @@ export abstract class BaseSearchService implements ISearchService {
     const uri = `/subscriptions/${subscriptionId}/providers/Microsoft.Web/locations/${location}/managedApis`;
     // const responseArray = await this.batchAzureResourceRequests(uri);
     const responseArray = await this.getAzureResourceRecursive(uri, undefined);
-    return this.moveGeneralInformation(responseArray);
+    const movedGeneralResponseArray = this.moveGeneralInformation(responseArray);
+    return this.removeUnsupportedConnectors(movedGeneralResponseArray);
```
Comment (preetriti1) [inline libs/logic-apps-shared/src/designer-client-services/lib/base/search.ts:182]: Filter unsupported and then move the general information

File: libs/logic-apps-shared/src/designer-client-services/lib/base/search.ts [hunk 2]
```diff
@@ -209,8 +217,7 @@ export abstract class BaseSearchService implements ISearchService {
       };
       // const response = await this.batchAzureResourceRequests(uri, queryParameters);
       const response = await this.getAzureResourceRecursive(uri, queryParameters);
-
-      return response;
+      return this.removeUnsupportedOperations(response);
```
Comment (preetriti1) [inline libs/logic-apps-shared/src/designer-client-services/lib/base/search.ts:220]: Don't do it in custom apis.. those are user deployed and managed and no need to run a iteration on it when we should not filter here. 
We should only do for managed apis

File: libs/logic-apps-shared/src/designer-client-services/lib/base/search.ts [hunk 3]
```diff
@@ -228,9 +235,8 @@ export abstract class BaseSearchService implements ISearchService {
       };
       // const response = await this.batchAzureResourceRequests(uri, queryParameters);
       const response = await this.getAzureResourceRecursive(uri, queryParameters);
-
       const locationFilteredResponse = response.filter((connector: any) => equals(connector.location, location));
-      return locationFilteredResponse;
+      return this.removeUnsupportedConnectors(locationFilteredResponse);
```
Comment (preetriti1) [inline libs/logic-apps-shared/src/designer-client-services/lib/base/search.ts:239]: Same remove from here too

File: libs/logic-apps-shared/src/designer-client-services/lib/base/search.ts [hunk 4]
```diff
@@ -248,6 +254,14 @@ export abstract class BaseSearchService implements ISearchService {
     return connectors;
   }
 
+  public removeUnsupportedOperations(operations: DiscoveryOpArray): DiscoveryOpArray {
+    return operations.filter((operation) => !this._unsupportedConnectorIds.includes(operation?.properties?.api?.id));
```
Comment (preetriti1) [inline libs/logic-apps-shared/src/designer-client-services/lib/base/search.ts:258]: I would suggest to normalize the connectorIds in your list and from the api.id to do the includes.. because it is a resource I'd and even if they have different casing they would be same resource so you need to be case insensitive here.

**Review by preetriti1 — CHANGES_REQUESTED** [review]

File: libs/logic-apps-shared/src/designer-client-services/lib/base/search.ts (hunk 4 above)
Comment (Elaina-Lee) [reply libs/logic-apps-shared/src/designer-client-services/lib/base/search.ts:257]: Can you help clarify 'normalizing the connectorIds in your list and from the api.id' - what would you mean by normalize here, to Lowercase those?

File: libs/logic-apps-shared/src/designer-client-services/lib/base/search.ts [hunk 5]
```diff
@@ -208,9 +217,7 @@ export abstract class BaseSearchService implements ISearchService {
         $filter: `properties/trigger eq null and type eq 'Microsoft.Web/customApis/apiOperations' and ${ISE_RESOURCE_ID} eq null`,
       };
       // const response = await this.batchAzureResourceRequests(uri, queryParameters);
-      const response = await this.getAzureResourceRecursive(uri, queryParameters);
-
-      return response;
+      return await this.getAzureResourceRecursive(uri, queryParameters);
```
Comment (preetriti1) [inline libs/logic-apps-shared/src/designer-client-services/lib/base/search.ts:220]: you can just do return this.getAzureResourceRecursive no need for await here

File: libs/logic-apps-shared/src/utils/src/lib/helpers/__test__/connectors.spec.tsx [hunk 6]
```diff
@@ -210,4 +212,50 @@ describe('utils/src/lib/helpers/connectors', () => {
...
+        '',
+        '/serviceProviders/Sql',
+      ]);
+      expect(normalizeConnectorIds([...armConnectorIds, '', '/serviceProviders/sql'], subscriptionId, location, true)).toEqual([
+        expectedConnectorId.toLowerCase(),
+        expectedConnectorId2.toLowerCase(),
+        '',
+        '/serviceProviders/Sql'.toLowerCase(),
+      ]);
+    });
```
Comment (preetriti1) [inline libs/logic-apps-shared/src/utils/src/lib/helpers/__test__/connectors.spec.tsx:259]: This should be in a separate describe since this is a difference function normalizeConnectorIds

**Review by preetriti1 — APPROVED** [review]
