### PR TITLE
Hide loading state for branching subgraph nodes

### LINKED ISSUE #1227: Switch case detail panel loading forever, never shows params
### Steps to Reproduce the Bug or Issue

1. Add a Switch node
2. Click the (+) button to add a case
3. Click the newly created Case
4. The panel should open and show a loading indicator

### Expected behavior

User should click the case node and see a panel where they can change the case settings

### Screenshots or Videos

image

### Platform And Browser

- Windows
- Chrome

AB#16065027

### PR DESCRIPTION
**Pull request by rllyy97**
## Main Changes
- Hiding loading state for branching subgraph nodes
- Switch case parameter is now shown correctly
- Fixes #1227

image

### CODE REVIEW

File: libs/designer/src/lib/ui/panel/panelroot.tsx [hunk 1]
```diff
@@ -211,7 +211,7 @@ export const PanelRoot = (): JSX.Element => {
       panelLocation={PanelLocation.Right}
       isCollapsed={collapsed}
       noNodeSelected={!selectedNode}
-      isLoading={!iconUri}
+      // isLoading={!iconUri}
```
Comment (preetriti1) [inline libs/designer/src/lib/ui/panel/panelroot.tsx:214]: What is this removing?

**Review by preetriti1 — APPROVED** [review]

File: libs/designer/src/lib/ui/panel/panelroot.tsx (hunk 1 above)
Comment (rllyy97) [reply libs/designer/src/lib/ui/panel/panelroot.tsx]: It was for the loading icon in the operation panel header, I just pushed another commit to also check if it's a branching node so this is also fixed now
