### PR TITLE
fix(designer): Show lock icon for actions with secure inputs/outputs

### LINKED ISSUE #2864: Standard: Operations with secure inputs or outputs enabled - Lock icon missing
### Describe the Bug

In a Standard workflow, on an operation (trigger or action) where you enable secure inputs or secure outputs, the lock icon should appear on the operation shape, like on operations in Consumption workflows.

**Consumption**
image

**Standard**
image

### Plan Type

Standard, but I assume Local too?

### Steps to Reproduce the Bug or Issue

1. Create a Standard logic app workflow.
2. Add a trigger or action that supports secure inputs and secure outputs.
3. Enable both secure inputs and secure outputs.

On the designer, no lock icon appears on the operation.

AB#24329637

AB#24389916

### PR DESCRIPTION
**Pull request by ccastrotrejo**
* [X] The commit message follows our guidelines
* [X] Tests for the changes have been added (for bug fixes/features)
* [ ] Docs have been added / updated (for bug fixes / features)

- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Fixes #2864 

- **What is the current behavior?** (You can also link to an open issue here)
Card footer doesn't show lock icon for secure inputs or outputs

- **What is the new behavior (if this is a feature change)?**
Card footer now shows lock icon when the action has secure inputs or outputs

- **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No

- **Please Include Screenshots or Videos of the intended change**:

Implementation example
Screenshot 2023-06-27 at 1 40 48 PM

Implementation in Standard

https://github.com/Azure/LogicAppsUX/assets/102700317/1b947670-0dad-4041-8947-c5741a17c3e0

Implementation in Consumption

https://github.com/Azure/LogicAppsUX/assets/102700317/2734b04f-d27d-45cb-bd95-d377d3c3cd5d

Implementation in Monitoring View
Screenshot 2023-06-27 at 1 59 00 PM

### CODE REVIEW

File: libs/designer-ui/src/lib/card/cardfooter.tsx [hunk 1]
```diff
@@ -54,6 +67,14 @@ export const CardFooter: React.FC<CardFooterProps> = ({ commentBox, connectionDi
     defaultMessage: 'Comment',
     description: 'This is for a label for a badge, it is used for screen readers and not shown on the screen.',
   });
+  const SECURE_INPUTS_OUTPUTS_TITLE = intl.formatMessage({
```
Comment (ccastrotrejo) [inline libs/designer-ui/src/lib/card/cardfooter.tsx:70]: Hi @ecfan, could you please check these two texts?

Comment (ecfan) [reply libs/designer-ui/src/lib/card/cardfooter.tsx:70]: The ones that mention "secure inputs and outputs"? They look OK to me.

**Review by ecfan — APPROVED** [review]

File: libs/designer-ui/src/lib/card/cardfooter.tsx (hunk 1 above)
Comment (ccastrotrejo) [reply libs/designer-ui/src/lib/card/cardfooter.tsx:70]: Thanks!

**Review by rllyy97 — APPROVED** [review]
