### PR TITLE
fix(designer): Update selector for retry history and add useMemo

### LINKED ISSUE #5215: LA STD- unable to see retry history on HTTP actions in for each loop
### Describe the Bug with repro steps 

Add HTTP action inside for each loop, let action fail with any 5xx or retriable error codes.

 Go to failed run and navigate to failed action, there is no retry tab at all

image

if you open the similar HTTP action outside loop it shows the retry

 and in HAR traces also we can find the retry history, but on UI its not showing

image

### What type of Logic App Is this happening in? 

Standard (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

edge, chrome

### Additional context 

*No response*

### PR DESCRIPTION
**Pull request by ccastrotrejo**
This pull request includes changes to enhance the functionality and efficiency of the retry panel in the monitoring UI, as well as improvements to the workflow state selectors. The most important changes include adding a new `useEffect` hook to update retry history when the current page changes, and simplifying the selector logic for fetching retry history.

* Removed redundant code in `handlePagerChange` function to avoid unnecessary state updates.

* Simplified `useRetryHistory` selector to directly fetch retry history from `nodesMetadata`.

* Added `useEffect` import to support the new hook.

Fixes #5215 

https://github.com/user-attachments/assets/fc240009-5897-43fc-8d2d-29fb00b4928d

### CODE REVIEW

File: libs/designer-ui/src/lib/monitoring/retrypanel/index.tsx [hunk 1]
```diff
@@ -20,6 +20,11 @@ export const RetryPanel: React.FC<RetryPanelProps> = ({ retryHistories, visible
     return calculateDuration(retryHistory.startTime, retryHistory.endTime);
   }, [retryHistory.endTime, retryHistory.startTime]);
 
+  useEffect(() => {
+    const newRetryHistory = retryHistories[currentPage - 1];
```
Comment (Elaina-Lee) [inline libs/designer-ui/src/lib/monitoring/retrypanel/index.tsx:24]: Would there be a reason why we are not using useMemo for this and using useEffect to update the value here?

Comment (hartra344) [reply libs/designer-ui/src/lib/monitoring/retrypanel/index.tsx:24]: I agree, that would probably be better and lead to fewer rerenders

File: libs/designer-ui/src/lib/monitoring/retrypanel/index.tsx [hunk 2]
```diff
@@ -20,6 +20,11 @@ export const RetryPanel: React.FC<RetryPanelProps> = ({ retryHistories, visible
     return calculateDuration(retryHistory.startTime, retryHistory.endTime);
   }, [retryHistory.endTime, retryHistory.startTime]);
 
+  useMemo(() => {
```
Comment (Elaina-Lee) [inline libs/designer-ui/src/lib/monitoring/retrypanel/index.tsx:23]: Followed up offline, but I would suggest with the correct usage of useMemo, it would look like this:

`const retryHistory = useMemo(() => retryHistories[currentPage - 1], [retryHistories, currentPage]);`

image

Comment (ccastrotrejo) [reply libs/designer-ui/src/lib/monitoring/retrypanel/index.tsx:23]: Thank you so much I will make the change

**Review by Elaina-Lee — APPROVED** [review]
