### PR TITLE
fix(Consumption): Changing error message for invalid expression due to double quotes.

### LINKED ISSUE #4111: Show descriptive error message in expression editor
### Describe the Bug with repro steps 

Create a simple flow.

When an item is created -> Compose. in compose, add an expression concat("1", "2") and try saving. It says expression is invalid. Can we add ' Expression is invalid. Please use single quote' when we know double quotation is used to represent a string ?

This is a basic fundamental scenario for users where they are getting really confused. In expression, we accept single quotation, in filter query, we accept double quotation, we need to make it super clear in UX.

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Chrome

### Additional context 

*No response*

### PR DESCRIPTION
**Pull request by valentina-vallalta**
In the Compose action, when inserting an expression, the expression will be invalid if it contains double quotes instead of single quotes for strings. This PR changes the error message to "The expression is invalid. Make sure to use single quotes." when an invalid expression contains a double quote to help the user understand that the error may be due to the use of double quotes over single quotes.

Fixes #4111

### CODE REVIEW

File: libs/designer-ui/src/lib/tokenpicker/tokenpickerfooter.tsx [hunk 1]
```diff
@@ -96,7 +100,12 @@ export function TokenPickerFooter({
     try {
       currExpression = ExpressionParser.parseExpression(expression.value);
     } catch (ex) {
-      setExpressionEditorError(invalidExpression);
+      if (expression.value.includes('"')) {
```
Comment (hartra344) [inline libs/designer-ui/src/lib/tokenpicker/tokenpickerfooter.tsx:103]: I wonder if there's a way we can generically add something to expression parser instead. this doesn't seem very scalable to other error types.

Comment (valentina-vallalta) [reply libs/designer-ui/src/lib/tokenpicker/tokenpickerfooter.tsx]: hello, I have reworked it so that is throws a different error in the parser if the problem is due to misused double quotes, let me know what you think!

File: libs/designer-ui/src/lib/tokenpicker/tokenpickerfooter.tsx [hunk 2]
```diff
@@ -68,7 +68,11 @@ export function TokenPickerFooter({
   });
   const invalidExpression = intl.formatMessage({
     defaultMessage: 'The expression is invalid.',
-    description: 'invalid expression alert',
+    description: 'Invalid expression alert',
+  });
+  const invalidExpressionQuotations = intl.formatMessage({
+    defaultMessage: 'The expression is invalid. Please use single quotes.',
```
Comment (ccastrotrejo) [inline libs/designer-ui/src/lib/tokenpicker/tokenpickerfooter.tsx:74]: Adding @ecfan to review this wording

File: Localize/lang/strings.json [hunk 3]
```diff
@@ -795,6 +795,7 @@
   "W+mUyI": "Next",
   "W070M2": "of {max}",
   "W6FdMh": "Required. The name of the new property.",
+  "W7kvPF": "The expression is invalid. Please use single quotes.",
```
Comment (ecfan) [inline Localize/lang/strings.json:798]: This scenario shouldn't use ["please"](https://learn.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/p/please): 

```suggestion
  "W7kvPF": "The expression is invalid. Make sure to use single quotes.",
```

File: libs/designer-ui/src/lib/tokenpicker/tokenpickerfooter.tsx (hunk 2 above)
Comment (ecfan) [inline libs/designer-ui/src/lib/tokenpicker/tokenpickerfooter.tsx:74]:
```suggestion
    defaultMessage: 'The expression is invalid. Make sure to use single quotes.',
```

File: libs/services/intl/src/compiled-lang/strings.en-XA.json [hunk 4]
```diff
@@ -11727,6 +11727,20 @@
...
     }
   ],
+  "W7kvPF": [
+    {
+      "type": 0,
+      "value": "["
+    },
+    {
+      "type": 0,
+      "value": "Ŧħḗḗ ḗḗẋƥřḗḗşşīǿǿƞ īş īƞṽȧȧŀīḓ. Ƥŀḗḗȧȧşḗḗ ŭŭşḗḗ şīƞɠŀḗḗ ɋŭŭǿǿŧḗḗş."
```
Comment (ecfan) [inline libs/services/intl/src/compiled-lang/strings.en-XA.json:11737]: Not sure how to fix this? Use wording as previously suggested.

**Review by ecfan — CHANGES_REQUESTED** [review]
Added feedback, thanks!

File: Localize/lang/strings.json (hunk 3 above)
Comment (valentina-vallalta) [reply Localize/lang/strings.json]: done!

File: libs/designer-ui/src/lib/tokenpicker/tokenpickerfooter.tsx (hunk 2 above)
Comment (valentina-vallalta) [reply libs/designer-ui/src/lib/tokenpicker/tokenpickerfooter.tsx]: done!

File: libs/services/intl/src/compiled-lang/strings.en-XA.json (hunk 4 above)
Comment (valentina-vallalta) [reply libs/services/intl/src/compiled-lang/strings.en-XA.json]: done! this file gets automatically updated based on the other ones

**Review by ecfan — APPROVED** [review]
Thanks!

**Review by rllyy97 — APPROVED** [review]

**Review by ccastrotrejo — APPROVED** [review]
