### PR TITLE
fix(designer-ui): Prevent text formatting in non-HTML inputs

### LINKED ISSUE #3700: Text in non-HTML editors can be formatted (e.g., bolded)
### Describe the Bug with repro steps

1. Open any workflow in the designer.
2. Ensure the open workflow has some action or trigger with a text-based input that is **NOT** an HTML editor.
3. Enter something in the above text-based input.
4. Highlight the entered text.
5. Hit Ctrl+B (or Cmd+B on Mac).

Expected: Nothing should happen.
Actual: Text becomes bold.

(Also works with italics using Ctrl+I, etc.)

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Workflow JSON

_No response_

### Screenshots or Videos

format-non-html

### Browser

Windows 11 / Chrome 119.0.6045.159.

### Additional context

_No response_

AB#25854136

### PR DESCRIPTION
**Pull request by ek68794998**
- **Please check if the PR fulfills these requirements**

* [x] The commit message follows our guidelines
* [ ] Tests for the changes have been added (for bug fixes/features)
* [ ] Docs have been added / updated (for bug fixes / features)

- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

Bug fix

- **What is the current behavior?** (You can also link to an open issue here)

Text can be bolded, italicized, etc. in non-HTML editors using keyboard shortcuts. (See #3700.)

- **What is the new behavior (if this is a feature change)?**

Plaintext editor is used when toolbar is not shown, preventing use of rich text. Fixes #3700.

- **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

No

- **Please Include Screenshots or Videos of the intended change**:

It's very difficult to show, but I tried my best using keystrokes in the GIF below.

format-non-html-fix

### CODE REVIEW

File: libs/designer-ui/src/lib/editor/base/index.tsx [hunk 1]
```diff
@@ -163,6 +164,8 @@ export const BaseEditor = ({
   };
 
   const id = useId('msla-described-by-message');
+  const TextPlugin = toolbar ? RichTextPlugin : PlainTextPlugin;
```
Comment (ek68794998) [inline libs/designer-ui/src/lib/editor/base/index.tsx:167]: Open question: Is `toolbar` here the best way to detect if we're in rich text mode?

Comment (ek68794998) [reply libs/designer-ui/src/lib/editor/base/index.tsx:167]: Looks like this is what's used on line 135, so should be safe.

Comment (Eric-B-Wu) [reply libs/designer-ui/src/lib/editor/base/index.tsx:167]: yeah this is fine, though I'm gonna create an item to move the toolbar prop into something a bit more inline with the HTML editor

**Review by Eric-B-Wu — APPROVED** [review]
