### PR TITLE
fix(vscode): Filter connectors and operations according to azure connection capabilities

### LINKED ISSUE #2836: VS Code: Able to see "Azure Function Operations" connector even after disabling/skipping the use of connectors from Azure
### Describe the Bug with repro steps

1.Create a new workflow app using VS Code and **DO NOT enable** Azure connectors to be used
2.Create a workflow (stateful or stateless)
3.Add a HTTP trigger to the workflow and save the workflow
4.Add an action after the trigger
5.Take note of the actions available to you, you should not be able to see "Azure Function Operations" connector.

**Expected:** Should **not** be able to see "Azure Function Operations" connector.
**Actual:** Able to see "Azure Function Operations" connector even after disabling/skipping the use of connectors from Azure

### What type of Logic App Is this happening in?

Standard (VSCode)

### Are you using Preview Designer or GA Designer

Preview

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

No

### Workflow JSON

```json
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {},
        "contentVersion": "1.0.0.0",
        "outputs": {},
        "triggers": {
            "When_a_HTTP_request_is_received": {
                "type": "Request",
                "kind": "Http"
            }
        },
        "parameters": {}
    },
    "kind": "Stateful"
}
```

### Screenshots or Videos

image
image
image

### Browser

VS Code

### Additional context

**Artifacts details:**

1.VS Code extension: [vscode-azurelogicapps-2.28.3.vsix](https://microsoft.sharepoint.com/:u:/t/LogicApps/ERQvUcsm27ZDqAk8h0IZFCQBnKEudkPL03CVtbYt1v_VMA?e=t0HVLO&xsdata=MDV8MDF8di1nb3Z1YmlsaXNoQG1pY3Jvc29mdC5jb218ZmM2NDU5N2YxZDQxNGVlYmVlYTcwOGRiNzM4MjM4YmN8NzJmOTg4YmY4NmYxNDFhZjkxYWIyZDdjZDAxMWRiNDd8MXwwfDYzODIzMDc3NTQ4NDkwNTEwOHxVbmtub3dufFRXRnBiR1pzYjNkOGV5SldJam9pTUM0d0xqQXdNREFpTENKUUlqb2lWMmx1TXpJaUxDSkJUaUk2SWsxaGFXd2lMQ0pYVkNJNk1uMD18MzAwMHx8fA%3d%3d&sdata=TDhwSU14VSsyOVNxNkErMVIyY0QyZkd4TGZwQTIzYktQYWxxM2ZHNnNTOD0%3d)
2.Nuget package:
[https://artprodeussu2.artifacts.visualstudio.com/A41bf5486-7392-4b7a-a7e3-a735c767e3b3/b32aa71e-8ed2-41b2-9d77-5bc261222004/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzc1MzA5MDMwL2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1/content?format=file&subPath=%2FMicrosoft.Azure.Workflows.WebJobs.Extension.1.28.2.nupkg](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fartprodeussu2.artifacts.visualstudio.com%2FA41bf5486-7392-4b7a-a7e3-a735c767e3b3%2Fb32aa71e-8ed2-41b2-9d77-5bc261222004%2F_apis%2Fartifact%2FcGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzc1MzA5MDMwL2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1%2Fcontent%3Fformat%3Dfile%26subPath%3D%252FMicrosoft.Azure.Workflows.WebJobs.Extension.1.28.2.nupkg&data=05%7C01%7Cv-govubilish%40microsoft.com%7Cfc64597f1d414eebeea708db738238bc%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638230775484905108%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=g10UtlCyrfuCJ3xEYvwnFQPrl%2Bm6XQ2kcVQMsojBn4U%3D&reserved=0)
3.Extension Bundle (CDN URL): [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting&data=05%7C01%7Cv-govubilish%40microsoft.com%7Ce347346c9dcc4a4cf80808db6b188892%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638221525391045919%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2BMcHLJsKeduA0dQVQ2CgOL5GzXjsVgOPWUrnxLtW%2Fnw%3D&reserved=0)
4.Extension Bundle (Direct Download): [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle.Workflows/1.28.2/Microsoft.Azure.Functions.ExtensionBundle.Workflows.1.28.2_any-any.zip](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting%2FExtensionBundles%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows%2F1.28.2%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows.1.28.2_any-any.zip&data=05%7C01%7Cv-govubilish%40microsoft.com%7Cfc64597f1d414eebeea708db738238bc%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638230775484905108%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=X3COeqQjGm9dM2gxR11Ry2QC76q7bwedZA1PmclN1jk%3D&reserved=0)

AB#24361195

### PR DESCRIPTION
**Pull request by ccastrotrejo**
* [X] The commit message follows our guidelines
* [X] Tests for the changes have been added (for bug fixes/features)
* [ ] Docs have been added / updated (for bug fixes / features)

- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Fixes #2836 

- **What is the current behavior?** (You can also link to an open issue here)
Functions to get the api connectors and operations don't filter the fetched data based on the capabilities of the workflow, this means that support azure connections.

- **What is the new behavior (if this is a feature change)?**
Functions now filter the connectors and operations based on if the apiHubServiceDetails has the subscription Id. This shouldn't affect portal as the workflow must be attached to a subscription id, whereas in local development isn't that way.

- **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
This affects these connectors/operations 
azureFunctionOperation -> Call an Azure function
apiManagementOperation -> Call an Azure API Management API

If user wants to use them, it will need to specify an azure connector/resource group when opening the designer in vscode

- **Please Include Screenshots or Videos of the intended change**:

Before without subscription ID (vscode)
Screenshot 2023-06-26 at 10 24 49 AM
Screenshot 2023-06-26 at 10 25 17 AM

After with subscription ID (vscode)
Screenshot 2023-06-26 at 10 19 05 AM

After without subscription ID (vscode)
Screenshot 2023-06-26 at 10 06 03 AM

After with subscription ID (standalone/portal)
Screenshot 2023-06-26 at 10 11 52 AM

### CODE REVIEW

**Review by Eric-B-Wu — APPROVED** [review]

File: libs/services/designer-client-services/src/lib/standard/search.ts [hunk 1]
```diff
@@ -125,3 +128,22 @@ function filterStateful(operation: DiscoveryOperation<BuiltInOperation> | Connec
...
+}
+
+function filterAPIOperations(
+  rawOperations: DiscoveryOperation<SomeKindOfAzureOperationDiscovery>[],
+  isAzureConnectorsEnabled: boolean
+): DiscoveryOperation<SomeKindOfAzureOperationDiscovery>[] {
+  return rawOperations.filter(
+    (rawOperation: DiscoveryOperation<SomeKindOfAzureOperationDiscovery>) => !needsAzureConnection(rawOperation) || isAzureConnectorsEnabled
+  );
+}
```
Comment (rllyy97) [inline libs/services/designer-client-services/src/lib/standard/search.ts:145]: On these two functions, if `isAzureConnectorsEnabled` is true it just returns the whole array, so we can pull that out of the filter functions (see above comment)

File: libs/services/designer-client-services/src/lib/standard/search.ts [hunk 2]
```diff
@@ -125,3 +128,22 @@ function filterStateful(operation: DiscoveryOperation<BuiltInOperation> | Connec
     ? operation.properties.capabilities.includes('Stateful') || !operation.properties.capabilities.includes('Stateless')
     : operation.properties.capabilities.includes('Stateless') || !operation.properties.capabilities.includes('Stateful');
 }
+
+function filterAPIConnectors(rawConnectors: Connector[], isAzureConnectorsEnabled: boolean): Connector[] {
+  return rawConnectors.filter((rawConnector: Connector) => {
+    return !equals(rawConnector.name, 'dataOperationNew') && (!needsAzureConnection(rawConnector) || isAzureConnectorsEnabled);
```
Comment (rllyy97) [inline libs/services/designer-client-services/src/lib/standard/search.ts:134]: What's the situation that was causing this exception to be needed?  Do we not want to see that connector when Azure operations are disabled?

File: libs/services/designer-client-services/src/lib/standard/search.ts [hunk 3]
```diff
@@ -115,7 +116,9 @@ export class StandardSearchService extends BaseSearchService {
       'api-version': apiVersion,
     };
     const response = await httpClient.get<{ value: Connector[] }>({ uri, queryParameters });
-    return [...response.value, ...getClientBuiltInConnectors(filterConnector)];
+    const filteredApiConnectors = filterAPIConnectors(response.value, this.options.apiHubServiceDetails.subscriptionId !== undefined);
```
Comment (rllyy97) [inline libs/services/designer-client-services/src/lib/standard/search.ts:119]: We should pull out the `isAzureConnectorsEnabled` as
```suggestion
const isAzureConnectorsEnabled = this.options.apiHubServiceDetails.subscriptionId !== undefined;
if (isAzureConnectorsEnabled) response.value = filterAPIConnectors(response.value)
```
to avoid any unnecessary filtering operations (will be faster, and won't run the filtering in portal)

**Review by rllyy97 — CHANGES_REQUESTED** [review]

File: libs/services/designer-client-services/src/lib/standard/search.ts (hunk 2 above)
Comment (ccastrotrejo) [reply libs/services/designer-client-services/src/lib/standard/search.ts:134]: There is a better explanation on this https://github.com/Azure/LogicAppsUX/issues/2836. But basically, for local development cx can decide to create workflows that don't require connections with remote resources. This implies that there is no subscription id involved.

Comment (rllyy97) [reply libs/services/designer-client-services/src/lib/standard/search.ts]: I mean specifically for the `!equals(rawConnector.name, 'dataOperationNew')` part of that function, that connector shouldn't require an azure connection, is there a reason we're hiding that connector specifically?

**Review by rllyy97 — APPROVED** [review]
