### PR TITLE
fix(designer): Replace missing state reassignment

### LINKED ISSUE #4227: Dynamic data for Teams "Post a message in a chat or channel" does not load
### Describe the Bug with repro steps 

1. Create a new workflow 
2. Add a Teams "Post a message in a chat or channel" action 
3. Choose "Channel" from the "Post In" dropdown 
4. Expand the "Team" dropdown 

Expected: The dropdown should show available teams.

 Actual: The dropdown is blank.

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

image

### Browser 

Chrome 121.0.6167.185, Windows 11 x64.

### Additional context 

Reproes in PAuto as well as designer standalone. Looks to have started happening [between v2.108.0 and v2.112.1](<https://github.com/Azure/LogicAppsUX/compare/v2.108.0%e2%80%a6v2.112.1>).

### PR DESCRIPTION
**Pull request by ek68794998**
- **Please check if the PR fulfills these requirements**

* [x] The commit message follows our guidelines
* [ ] Tests for the changes have been added (for bug fixes/features)
* [ ] Docs have been added / updated (for bug fixes / features)

- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

Bug fix

- **What is the current behavior?** (You can also link to an open issue here)

Dynamic inputs do not populate due to a regression in #4140. See #4227 for details of issue & fix.

Offending change being reverted:

image

- **What is the new behavior (if this is a feature change)?**

Dynamic inputs work properly. Closes #4227.

- **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

No

- **Please Include Screenshots or Videos of the intended change**:

image

### CODE REVIEW

File: libs/designer/src/lib/core/state/operation/operationMetadataSlice.ts [hunk 1]
```diff
@@ -259,7 +259,7 @@ export const operationMetadataSlice = createSlice({
 
       const dependencies = getInputDependencies(inputParameters, rawInputs, swagger);
       if (dependencies) {
-        dependencies.inputs = { ...dependencies.inputs, ...dependencies };
+        state.dependencies[nodeId].inputs = { ...state.dependencies[nodeId].inputs, ...dependencies };
```
Comment (ek68794998) [inline libs/designer/src/lib/core/state/operation/operationMetadataSlice.ts:262]: I think @rllyy97 will want to update this code to be more like later in the file:

image

However, in the interest of a safe & fast hotfix, I've reverted to the previous code verbatim here.

**Review by rllyy97 — APPROVED** [review]
