### PR TITLE
fix(designer): Fix Go to operation panel not panning to selected node

### LINKED ISSUE #6732: In the Designer, seaching for an action by name and selecting no longer navigates to the corresponding action in the graphical display.
### Describe the Bug with repro steps 

Logic App Standard

 Select workflow

 Select Designer or Run History

 Click the magnifying glass icon ("Search workflow actions")

 Select an action in the popup menu. An editor dialog opens; however, the corresponding action is no longer found in the graphical display of the action

### What type of Logic App Is this happening in? 

Standard (Portal)

### Which operating system are you using? 

Windows

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

```json

```

### Screenshots or Videos

This affects mutliple workflows in standard logic app in multiple environments.

### Browser

Edge, Chrome

### Additional context

*No response*

### PR DESCRIPTION
**Pull request by hartra344**
## Commit Type
- [ ] feature - New functionality
- [x] fix - Bug fix
- [ ] refactor - Code restructuring without behavior change
- [ ] perf - Performance improvement
- [ ] docs - Documentation update
- [ ] test - Test-related changes
- [ ] chore - Maintenance/tooling

## Risk Level
- [x] Low - Minor changes, limited scope
- [ ] Medium - Moderate changes, some user impact
- [ ] High - Major changes, significant user/system impact

## What & Why
This PR fixes an issue where clicking an operation in the "Go to operation" search panel doesn't pan the canvas to the selected node. The problem occurred when nodes were inside collapsed graphs - the focus was being set before the graph expansion animation completed, causing the panning logic to have incorrect node position data.

The fix adds a 100ms delay before setting focus, ensuring React Flow has finished rendering the expanded nodes. This allows the CanvasFinder component to correctly calculate the target position and pan the canvas to center on the selected node.

## Impact of Change
- **Users**: Improved navigation experience - clicking on operations in the search panel now reliably pans to show the selected node
- **Developers**: No API changes
- **System**: Minimal impact - adds a small timeout before focusing

## Test Plan
- [ ] Unit tests added/updated
- [ ] E2E tests added/updated
- [x] Manual testing completed
- [x] Tested in: Standalone designer with nested/collapsed operations

## Contributors
- @mlibenocg (issue reporter)

## Screenshots/Videos

https://github.com/user-attachments/assets/44f3f895-2195-4ee6-82f8-b8f6589b52b5

Fixes #6732

### CODE REVIEW

**Review by rllyy97 — APPROVED** [review]

File: libs/designer/src/lib/ui/panel/nodeSearchPanel/nodeSearchPanel.tsx [hunk 1]
```diff
@@ -35,8 +35,11 @@ const NodeSearchCard = ({ node }: { node: string }) => {
         showImage={true}
         onClick={(_: string) => {
           dispatch(collapseGraphsToShowNode(node));
-          dispatch(setFocusNode(node));
           dispatch(changePanelNode(node));
+          // Delay focus to allow graph expansion to complete
+          setTimeout(() => {
+            dispatch(setFocusNode(node));
+          }, 100);
```
Comment (takyyon) [inline libs/designer/src/lib/ui/panel/nodeSearchPanel/nodeSearchPanel.tsx:45]: Is that just a normal average time for graph expansion or something we are just trying to play and test?

**Review by takyyon — APPROVED** [review]

File: libs/designer/src/lib/ui/panel/nodeSearchPanel/nodeSearchPanel.tsx (hunk 1 above)
Comment (hartra344) [reply libs/designer/src/lib/ui/panel/nodeSearchPanel/nodeSearchPanel.tsx:45]: 1. Animation timing - React Flow and Fluent UI typically use animation durations between 200-350ms for expand/collapse transitions. 100ms ensures we're well into the
  animation but not waiting unnecessarily long.
  2. User perception - Delays under 100ms are generally imperceptible to users, while delays over 200ms start to feel sluggish. 100ms maintains a responsive feel.
  3. Rendering cycle - It provides enough time for:
    - React to re-render with the expanded graph state
    - React Flow to recalculate node positions
    - The browser to complete layout calculations
