### PR TITLE
fix(vscode): Update error handle on HTTP Post API call

### LINKED ISSUE #7390: Service Bus connection strings fail with topic-level shared access key
### Describe the Bug with repro steps

When adding a service bus connection with a topic-level shared access key, an error is thrown.  This happens in both the portal UI and VSC.

VSC error:
```
DataCloneError: Failed to execute 'postMessage' on 'MessagePort': function(e,n){const i=n.getContentType()||"",r=i.indexOf("application/json")>-1,a=Mo.isObject(e);if(a&&Mo.isHTM...<omitted>...e} could not be cloned.
```

Portal error:
```
Failed to create connection: {"Code":"BadRequest","Message":"Encountered an error (InternalServerError) from host runtime.","Target":null,"Details":[{"Message":"Encountered an error (InternalServerError) from host runtime."},{"Code":"BadRequest"},{"ErrorEntity":{"Code":"BadRequest","Message":"Encountered an error (InternalServerError) from host runtime."}}],"Innererror":null}
```

In VSC, you can get further output details when clicking Create new:
```
[2025-05-30T10:24:16.736Z] Error message: correlationId='eb36b6b5-c196-47f1-bc81-bcb93a8760f4', operationName='serviceBus.ServiceBusServiceOperationsProvider.HandleException', message='InvalidSignature: The token has an invalid signature. TrackingId:0b9f289b-4c48-4a7a-95ea-cd0482362f4c, SystemTracker:NoSystemTracker, Timestamp:2025-05-30T10:24:20
[2025-05-30T10:24:16.737Z] Status: 401 (Unauthorized)
[2025-05-30T10:24:16.737Z] 
[2025-05-30T10:24:16.737Z] Content:
[2025-05-30T10:24:16.737Z] <Error><Code>401</Code><Detail>InvalidSignature: The token has an invalid signature. TrackingId:0b9f289b-4c48-4a7a-95ea-cd0482362f4c, SystemTracker:NoSystemTracker, Timestamp:2025-05-30T10:24:20</Detail></Error>
```

1. Prepare a service bus with a topic
2. Inside the topic setup a shared access key for the topic (give it manage rights for giggles)
3. Copy the primary connection string for the new shared access key
4. Inside a Logic App (standard) workflow, add a new service bus connector for "When messages are available in a topic subscription (peek-lock)"
5. Enter in your clipboard contents of the connection string, it should be in the format of: Endpoint=sb://{myservicebus}.servicebus.windows.net/;SharedAccessKeyName={MyNewKey};SharedAccessKey=XXX;EntityPath={MyTopic}
6. Witness confusing errors

This issue does not occur when using a SAS key from the service bus' namespace root access policies.  On face value, it seems to be that the connector does not understand the EntityPath query parameter.  While this is a workaround, it's not especially liked for the security reasons of granting access to all topics and queues in the namespace.

The error is similar #7186, though the scenario is different.

### What type of Logic App Is this happening in?

Standard (VSCode)

### Which operating system are you using?

Windows

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Workflow JSON

```json

```

### Screenshots or Videos

Image

Image

### Browser

Firefox & VSC

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ccastrotrejo**
## Commit Type

- [ ] feature - New functionality
- [X] fix - Bug fix
- [ ] refactor - Code restructuring without behavior change
- [ ] perf - Performance improvement
- [ ] docs - Documentation update
- [ ] test - Test-related changes
- [ ] chore - Maintenance/tooling

## Risk Level

- [ ] Low - Minor changes, limited scope
- [X] Medium - Moderate changes, some user impact - **This will impact all of the POST API calls that are made through the designer in vscode**
- [ ] High - Major changes, significant user/system impact

## What & Why

- **What**: Try/catch statement in the HTTP POST API Call wasn't considering the actual API call, therefore the error wasn't getting handle correctly.
- **Why**: Users started to notice weird and nonsense errors in the UI when the POST API call was made

## Impact of Change

- **Users**: HTTP POST API calls will throw/return the proper error message and users will be able to see the root cause of it
- **Developers**: Extended the try/catch to also cover the API call 
- **System**: Nothing changed

## Test Plan

- [X] Unit tests added/updated
- [ ] E2E tests added/updated
- [ ] Manual testing completed
- [ ] Tested in: 

## Screenshots/Videos

CleanShot 2025-06-19 at 15 52 41@2x
CleanShot 2025-06-19 at 15 36 34@2x

Fix #7390

### CODE REVIEW

File: libs/vscode-extension/src/lib/services/httpClient.ts [hunk 1]
```diff
@@ -87,19 +87,24 @@ export class HttpClient implements IHttpClient {
...
+        throw response;
+      }
+
+      try {
+        return typeof response.data === 'string' ? JSON.parse(response.data) : response.data;
+      } catch {
+        return response.data as any;
+      }
+    } catch (error: any) {
+      throw error?.response?.data ?? error;
```
Comment (takyyon) [inline libs/vscode-extension/src/lib/services/httpClient.ts]:
```suggestion
      throw error?.response?.data ?? error?.response ?? error;
```
