### PR TITLE
fix(designer): Regression where array editor no longer serialized casted value

### LINKED ISSUE #4001: `ContentBytes` field of "Send an email" action is blanked if `suppressCasting` is `false`
### Describe the Bug with repro steps

1. Open any workflow
2. Add an Outlook 365 "Send an email (V2)" action
3. Add the optional "Attachments" field
4. Put any content (e.g., "aaaaa") in the "Content" property of the attachment
5. Switch to code view
6. Check the `ContentBytes` field

Expected: `"ContentBytes": "@{base64("aaaaa")}"`
Actual: `"ContentBytes": ""`

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Workflow JSON

_No response_

### Screenshots or Videos

image

image

### Browser

Chrome 120, Windows 11.

### Additional context

This is related to the following changes, which changed how `suppressCasting` was handled as well as how tokens were serialized (`$[ ]$` versus `@{ }`):

- #3873
- #3849

Here are some details from our Teams chat:

image

### PR DESCRIPTION
**Pull request by Eric-B-Wu**
Fixes #4001 
fixCastSerialization

### CODE REVIEW

**Review by hartra344 — APPROVED** [review]

File: libs/designer-ui/src/lib/arrayeditor/util/serializecollapsedarray.ts [hunk 1]
```diff
@@ -71,11 +71,11 @@ export const parseSimpleItems = (
   // Beautify ValueSegment
   try {
     const nodeMap = new Map<string, ValueSegment>();
-    const stringValueUncasted = JSON.stringify(JSON.parse(convertSegmentsToString(uncastedArraySegments, nodeMap)), undefined, 4);
     const stringValueCasted = JSON.stringify(JSON.parse(convertSegmentsToString(castedArraySegments, nodeMap)), undefined, 4);
+    const stringValueUncasted = JSON.stringify(JSON.parse(convertSegmentsToString(uncastedArraySegments, nodeMap)), undefined, 4);
```
Comment (takyyon) [inline libs/designer-ui/src/lib/arrayeditor/util/serializecollapsedarray.ts:75]: Nothing to block this PR but we should create a helper function to stringify the json properly and use it in all the places to make it easier to maintain and add a particular note explaining why we need to do this.

basically, something like - 

`const stringifyJson: (json: string) => JSON.stringify(JSON.parse(json), undefined, 4);`
