### PR TITLE
fix(designer): dictionary and array editor collapsed views erroring

### LINKED ISSUE #2699: Dictionary editor shows invalid json when content in value field contains new lines
### Describe the Bug with repro steps

1. Add any action with dictionary editor.
2. In the value field start entering some tokens and text with new line.

Actual: It shows invalid parameters although it can be stringified

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Generally Available

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Workflow JSON

_No response_

### Screenshots or Videos

_No response_

### Browser

Any

### Additional context

Incident - https://portal.microsofticm.com/imp/v3/incidents/details/395701603/home

AB#24208544

### PR DESCRIPTION
**Pull request by Eric-B-Wu**
- **Please check if the PR fulfills these requirements**

- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
bugfix

- **What is the current behavior?** (You can also link to an open issue here)
Adding a new line in dictionary and array editor would result in validation errors

- **What is the new behavior (if this is a feature change)?**
1. New lines no longer cause validation errors in json objects
2. Array editor doesn't crash designer when serializing in collapsed view

- **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

- **Please Include Screenshots or Videos of the intended change**:
bugfix

bugfix2

Fixes #2699

### CODE REVIEW

File: libs/designer-ui/src/lib/arrayeditor/collapsedarray.tsx [hunk 1]
```diff
@@ -23,7 +23,6 @@ export interface CollapsedArrayProps {
 
 export const CollapsedArray = ({
   labelProps,
-  isValid = true,
```
Comment (Eric-B-Wu) [inline libs/designer-ui/src/lib/arrayeditor/collapsedarray.tsx:26]: here we were doing validation checks within the editor as well as the parameter validation to enable/disable the toggle button. Removed this so there would never be the case of 2 error messages showing.
