### PR TITLE
fix(designer-ui): Retain tokens inserted into HTML editor if they contain `}`

### LINKED ISSUE #4195: Tokens inserted into HTML editor are lost if they contain `}`
### Describe the Bug with repro steps 

1. In any workflow, add SharePoint's "Create new folder" action. 
2. Fill in the required action parameters. 
3. Add an action after it which has an HTML editor. 
4. In the HTML editor, insert the token "Link to item" from the "Create new folder" action. 
5. Close the panel (or switch tabs) and return to the view. 

Expected: Token should be inserted and remain in the field.

 Actual: Token is replaced with `']}`.

Does not repro with non-HTML editors.

### What type of Logic App Is this happening in? 

Standard (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

html-bracket-deleted

### Browser 

Chrome 121.0.6167.185, Windows 11 x64.

### Additional context 

This likely occurs because of how pasted tokens are parsed, and the existence of `}` in the token is telling the editor that it's the end of the token.

### PR DESCRIPTION
**Pull request by ek68794998**
- **Please check if the PR fulfills these requirements**

* [x] The commit message follows our guidelines
* [ ] Tests for the changes have been added (for bug fixes/features)
* [ ] Docs have been added / updated (for bug fixes / features)

- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

Bug fix

- **What is the current behavior?** (You can also link to an open issue here)

If a token containing `}` is added to the HTML editor, it will disappear: #4195

- **What is the new behavior (if this is a feature change)?**

Tokens are now properly retained even if they contain a `{`. Note: If a token contains `@{`, it may have issues with parsing.

Closes #4195.

- **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

I don't think so, though a lot of internal signatures have changed to make `nodeMap` non-optional.

- **Please Include Screenshots or Videos of the intended change**:

html-bracket-working

### CODE REVIEW

File: libs/designer-ui/src/lib/editor/base/utils/editorToSegment.ts [hunk 1]
```diff
@@ -32,33 +33,83 @@ const getChildrenNodesToSegments = (node: ElementNode, segments: ValueSegment[],
...
+  let currSegmentType: ValueSegmentType = ValueSegmentType.LITERAL;
+  let isInQuotedString = false;
+  let segmentSoFar = '';
+
+  for (let currIndex = 0; currIndex < value.length; currIndex++) {
+    const currChar = value[currIndex];
+    const nextChar = value[currIndex + 1];
+
+    if (currChar === `'`) {
+      if (isInQuotedString) {
```
Comment (ek68794998) [inline libs/designer-ui/src/lib/editor/base/utils/editorToSegment.ts:60]: This should only apply inside tokens.

Comment (ek68794998) [reply libs/designer-ui/src/lib/editor/base/utils/editorToSegment.ts:60]: Fixed in 87c680d96.

**Comment by ek68794998** [comment]
If there are any test cases you'd like me to add and validate, let me know.

**Review by Eric-B-Wu — APPROVED** [review]
