### PR TITLE
fix(vscode): Remove never from copy settings from publish directory in dotnet projects

### LINKED ISSUE #5208: Deployment in nuget artifact is failing
### Describe the Bug with repro steps 

1. Create a new Logic App Project 
2. Add a workflow to your local project 
3. Open the workflow.json file in designer and author a new workflow

 a. Add http request Trigger

 b. Add a compose action here with custom text

 c. Add a ServiceBus action. From the add new paramter dropdown add content and add random text in JSON format like {"a":"b"}

 d. Add a send email action with the body being the output of the compose action (step b)

 e. Add a new connection to your email action

 f. Add http response action 
4. Press F5 to build and run your project 
5. Run the workflow

 a. Open overview page. Right + Click on workflow.json file and "Overview"

 b. Copy call back URL from the overview page

 c. Send the http request POST via Postman and wait for the response 
6. Refresh the overview page and your should see your local run 
7. Open the monitoring view for your run from the overview page 
8. Verify the run details and action inputs and output 
9. Convert the project into nuget based 
10. Deploy the workflow to azure logic app 

**Expected:** Deployment should get successful

**Actual:**Deployment **not** get successful

### What type of Logic App Is this happening in? 

Standard (VSCode)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

```json
Connection.JSON

{
  "serviceProviderConnections": {
    "serviceBus": {
      "parameterValues": {
        "connectionString": "@appsetting('serviceBus_connectionString')"
      },
      "parameterSetName": "connectionString",
      "serviceProvider": {
        "id": "/serviceProviders/serviceBus"
      },
      "displayName": "abcd"
    }
  },
  "managedApiConnections": {
    "office365-1": {
      "api": {
        "id": "/subscriptions/@{appsetting('WORKFLOWS_SUBSCRIPTION_ID')}/providers/Microsoft.Web/locations/@{appsetting('WORKFLOWS_LOCATION_NAME')}/managedApis/office365"
      },
      "connection": {
        "id": "/subscriptions/@{appsetting('WORKFLOWS_SUBSCRIPTION_ID')}/resourceGroups/@{appsetting('WORKFLOWS_RESOURCE_GROUP_NAME')}/providers/Microsoft.Web/connections/office365-3"
      },
      "connectionRuntimeUrl": "@parameters('office365-1-ConnectionRuntimeUrl')",
      "authentication": "@parameters('office365-1-Authentication')"
    }
  }
}




Workflow.JSON

{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {
            "Execute_JavaScript_Code": {
                "type": "JavaScriptCode",
                "inputs": {
                    "code": "return \"hello inline\""
                },
                "runAfter": {}
            },
            "Compose": {
                "type": "Compose",
                "inputs": "abcde",
                "runAfter": {
                    "Execute_JavaScript_Code": [
                        "SUCCEEDED"
                    ]
                }
            },
            "Send_message": {
                "type": "ServiceProvider",
                "inputs": {
                    "parameters": {
                        "entityName": "test1",
                        "message": {
                            "contentData": {
                                "a": "b"
                            }
                        }
                    },
                    "serviceProviderConfiguration": {
                        "connectionName": "serviceBus",
                        "operationId": "sendMessage",
                        "serviceProviderId": "/serviceProviders/serviceBus"
                    }
                },
                "runAfter": {
                    "Compose": [
                        "SUCCEEDED"
                    ]
                }
            },
            "Send_an_email_(V2)": {
                "type": "ApiConnection",
                "inputs": {
                    "host": {
                        "connection": {
                            "referenceName": "office365-1"
                        }
                    },
                    "method": "post",
                    "body": {
                        "To": "v-govubilish@microsoft.com",
                        "Subject": "p0 nuget",
                        "Body": "<p class=\"editor-paragraph\">@{outputs('Compose')}</p>",
                        "Importance": "Normal"
                    },
                    "path": "/v2/Mail"
                },
                "runAfter": {
                    "Send_message": [
                        "SUCCEEDED"
                    ]
                }
            },
            "Response": {
                "type": "Response",
                "kind": "Http",
                "inputs": {
                    "statusCode": 200,
                    "body": "@{outputs('Execute_JavaScript_Code')}\n@{parameters('a')}\n@{parameters('z')}"
                },
                "runAfter": {
                    "Send_an_email_(V2)": [
                        "SUCCEEDED"
                    ]
                }
            }
        },
        "contentVersion": "1.0.0.0",
        "outputs": {},
        "triggers": {
            "When_a_HTTP_request_is_received": {
                "type": "Request",
                "kind": "Http"
            }
        }
    },
    "kind": "Stateful"
}
```

### Screenshots or Videos

image

ss1

### Browser

VS Code

### Additional context

VSIX version :4.44.0

 Nuget Version : 1.81.4

### PR DESCRIPTION
**Pull request by ccastrotrejo**
This pull request to `apps/vs-code-designer` introduces a new function to allow local settings to be published to the directory and integrates this functionality into the existing workflow. The most important changes include adding the new function, updating imports, and modifying the build file update process.

* Added the `allowLocalSettingsToPublishDirectory` function to modify the XML build file and enable local settings to be published to the directory.

* Updated imports to include the new `allowLocalSettingsToPublishDirectory` function.
*  Updated imports to include `localSettingsFileName` from `../../../constants`.

*  Integrated the `allowLocalSettingsToPublishDirectory` function into the `updateBuildFile` function to update the XML build file accordingly.

Fixes #5208

### CODE REVIEW

**Review by takyyon — APPROVED** [review]

File: apps/vs-code-designer/src/app/utils/codeless/updateBuildFile.ts [hunk 1]
```diff
@@ -124,6 +124,32 @@ export function updateFunctionsSDKVersion(xmlBuildFile: Record<string, any>, dot
...
+ * @param context - The action context.
+ * @param xmlBuildFile - The XML build file to update.
+ * @returns The updated XML build file.
+ */
+export function allowLocalSettingsToPublishDirectory(context: IActionContext, xmlBuildFile: Record<string, any>): Record<string, any> {
+  try {
+    for (const itemGroup of xmlBuildFile['Project']['ItemGroup']) {
+      if ('None' in itemGroup) {
+        for (const item of itemGroup['None']) {
+          if (item['$']['Update'] === localSettingsFileName) {
```
Comment (rllyy97) [inline apps/vs-code-designer/src/app/utils/codeless/updateBuildFile.ts:138]: Are the `item['$']['Update']` references always going to be there or is there a chance they might be missing?  If they could be missing it might be best to optionally access them
ie. `item?.['$']?.['Update']`

**Review by rllyy97 — APPROVED** [review]

File: apps/vs-code-designer/src/app/utils/codeless/updateBuildFile.ts (hunk 1 above)
Comment (ccastrotrejo) [reply apps/vs-code-designer/src/app/utils/codeless/updateBuildFile.ts:138]: Yes, its expected that the schema remains the same, however it would be safer to add the optional access operator. I will add it, thanks!
