### PR TITLE
fix(designer): Remove tokens from a node when a node is deleted

### LINKED ISSUE #2343: Automatically remove output tokens of deleted nodes from parameter inputs
### Describe the Bug with repro steps 

1. Add any trigger 
2. Add two actions where in the second (last) action you are using an output token from the first action 
3. Remove the first action 
4. Observe token is persisted 
5. Try to save as-is and observe save failure 

### What type of Logic App Is this happening in? 

Standard (Portal)

### Are you using Preview Designer or GA Designer 

Preview

### Workflow JSON 

```json
{
  "definition": {
    "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
    "actions": {
      "Compose": {
        "type": "Compose",
        "inputs": "@body('Get_my_profile_(V2)')?['city']",
        "runAfter": {}
      }
    },
    "contentVersion": "1.0.0.0",
    "outputs": {},
    "triggers": {
      "When_the_current_weather_changes": {
        "type": "ApiConnection",
        "inputs": {
          "host": {
            "connection": {
              "referenceName": "msnweather"
            }
          },
          "method": "get",
          "path": "/trigger/current/weather/@{encodeURIComponent('Bellevue')}",
          "queries": {
            "Measure": "Temperature",
            "When": "Is equal to",
            "Target": 40,
            "units": "Metric"
          }
        },
        "recurrence": {
          "interval": 3,
          "frequency": "Minute"
        }
      }
    }
  },
  "connectionReferences": {
    "msnweather": {
      "api": {
        "id": "/subscriptions/e1f4ebc5-f80b-40c0-9027-93c34668bf5d/providers/Microsoft.Web/locations/eastus/managedApis/msnweather"
      },
      "connection": {
        "id": "/subscriptions/e1f4ebc5-f80b-40c0-9027-93c34668bf5d/resourceGroups/designer/providers/Microsoft.Web/connections/msnweather-1"
      },
      "connectionName": "msnweather-1",
      "authentication": {
        "type": "ManagedServiceIdentity"
      }
    }
  },
  "parameters": {}
}
```

### Screenshots or Videos

image

### Browser

Edge

### Additional context

This only seems to repro in preview designer, not able to repro in GA designer - the token gets automatically deleted

### PR DESCRIPTION
**Pull request by hartra344**
fixes #2343

This pull request primarily focuses on improving the handling of parameters and tokens within workflows and operations. The changes include modifying the `Parse_JSON` and `Filter_array` inputs in `Panel.json`, adding new tests in `tokenRemoval.spec.ts`, and updating the `delete.ts` and `operationMetadataSlice.ts` files to better manage tokens and parameters. The `workflowParametersPanel.tsx` file was also updated to use the new `deleteWorkflowParameter` function.

Key Changes:

* [`__mocks__/workflows/Panel.json`](diffhunk://#diff-217ae0e3f4cbdd019623860b9c5c30f8d8154d85c4b9fe4247e80ad39b4a7f58L37-R37): Modified the `content` input of `Parse_JSON` to include an additional parameter and changed the `from` input of `Filter_array` to include a test string. [[1]](diffhunk://#diff-217ae0e3f4cbdd019623860b9c5c30f8d8154d85c4b9fe4247e80ad39b4a7f58L37-R37) [[2]](diffhunk://#diff-217ae0e3f4cbdd019623860b9c5c30f8d8154d85c4b9fe4247e80ad39b4a7f58L70-R70)

* [`e2e/designer/tokenRemoval.spec.ts`](diffhunk://#diff-40403c79907f771d8e7b1e1e05be8490d591bde15b702d49732dbbea194bf2e0R1-R35): Added new tests for checking the removal of tokens from parameters when an operation or variable is deleted.

* [`libs/designer/src/lib/core/actions/bjsworkflow/delete.ts`](diffhunk://#diff-8df26d60c06080c30206ea9b35fae88ca4b26cf36ca92febcd77f43804983803L1-R7): Updated the file to include the `removeAllTokensFromNode` function which removes all tokens from a node or parameter. Also, the `deleteWorkflowParameter` function was added to delete a workflow parameter and remove all associated tokens. [[1]](diffhunk://#diff-8df26d60c06080c30206ea9b35fae88ca4b26cf36ca92febcd77f43804983803L1-R7) [[2]](diffhunk://#diff-8df26d60c06080c30206ea9b35fae88ca4b26cf36ca92febcd77f43804983803R19-R20) [[3]](diffhunk://#diff-8df26d60c06080c30206ea9b35fae88ca4b26cf36ca92febcd77f43804983803R32-R35) [[4]](diffhunk://#diff-8df26d60c06080c30206ea9b35fae88ca4b26cf36ca92febcd77f43804983803L41-R113)

* [`libs/designer/src/lib/core/state/operation/operationMetadataSlice.ts`](diffhunk://#diff-7234d29126221e752743c69e731dae3621424f8f4f7545420e494ebc7a2ff97dL6-R6): Updated the file to include the `removeAllTokensFromNode` function which removes all tokens from a node or parameter. [[1]](diffhunk://#diff-7234d29126221e752743c69e731dae3621424f8f4f7545420e494ebc7a2ff97dL6-R6) [[2]](diffhunk://#diff-7234d29126221e752743c69e731dae3621424f8f4f7545420e494ebc7a2ff97dR22) [[3]](diffhunk://#diff-7234d29126221e752743c69e731dae3621424f8f4f7545420e494ebc7a2ff97dR356-R381) [[4]](diffhunk://#diff-7234d29126221e752743c69e731dae3621424f8f4f7545420e494ebc7a2ff97dR602)

* [`libs/designer/src/lib/ui/panel/workflowParametersPanel/workflowParametersPanel.tsx`](diffhunk://#diff-c83531fb2965d527a640c1234869dd09abacb1ef3791cb2af07d843b6ce4498fR1-R4): Updated the file to use the new `deleteWorkflowParameter` function instead of the old `deleteParameter` function. [[1]](diffhunk://#diff-c83531fb2965d527a640c1234869dd09abacb1ef3791cb2af07d843b6ce4498fR1-R4) [[2]](diffhunk://#diff-c83531fb2965d527a640c1234869dd09abacb1ef3791cb2af07d843b6ce4498fL12-R21)

### CODE REVIEW

**Review by rllyy97 — APPROVED** [review]
Looks good to me, one thought I had reviewing this, in the future I think it might be good to consider showing a warning before deleting a workflow parameter just saying which nodes are still using the parameter and that the tokens will be deleted.  Might be good to have something similar for normal tokens / deleting actions

File: libs/designer/src/lib/core/actions/bjsworkflow/delete.ts [hunk 1]
```diff
@@ -38,21 +44,73 @@ export const deleteOperation = createAsyncThunk(
...
+          if (isTokenValueSegment(value) && value.token) {
+            if (isVariableToken(value.token)) {
+              if (variables?.find((v) => v.name === value.token?.name)) {
+                paramValue = paramValue.filter((v) => v.id !== value.id);
+                updatedValue = true;
+              }
+            } else if (parameterId && isParameterToken(value.token) && value.token?.name === parameterId) {
+              paramValue = paramValue.filter((v) => v.id !== value.id);
+              updatedValue = true;
+            } else if (nodeId && value.token?.actionName === nodeId) {
```
Comment (preetriti1) [inline libs/designer/src/lib/core/actions/bjsworkflow/delete.ts:87]: thia s not true for trigger nodes.
