### PR TITLE
fix(vscode): Add validation for error response structure

### LINKED ISSUE #5142: Invalid connection blanks designer when editing connection
### Describe the Bug with repro steps 

1. Create an invalid connection (e.g. in app SQL connection with "tbd" for connection string) 
2. Select an action that requires dynamic input (e.g. SQL Connection exec stored procedure) 
3. Try to edit a dynamic field (e.g. Stored Procedure name) 

Expected result - the action fail to load the information from the endpoint, but allow you to enter a manual value (previous behavior)

 Actual result - the designer surface blanks out and you can't continue editing the logic apps. Any previous updates will be lots.

This has been observed on a meeting with a customer with the same type of issue for keyvault in app connector, so it is not a SQL specific issue.

### What type of Logic App Is this happening in? 

Standard (VSCode)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

[https://github.com/user-attachments/assets/d7881f90-f7c6-4fa4-82bc-e8b80dc9f5a3](<https://github.com/user-attachments/assets/d7881f90-f7c6-4fa4-82bc-e8b80dc9f5a3>)

### Browser 

N/A

### Additional context 

*No response*

### PR DESCRIPTION
**Pull request by ccastrotrejo**
This pull request primarily involves changes to error handling in two functions, `loadDynamicValuesForParameter` and `fetchDynamicValuesForParameter`, within the `libs/designer/src/lib/core/utils/parameters/helper.ts` file. The changes improve the way error messages are extracted from the error object, allowing for more robust error handling.

* In both `loadDynamicValuesForParameter` and `fetchDynamicValuesForParameter`, the error message extraction logic has been modified. Now, it first checks if the error has a `response` property before trying to extract the `data` property. If there's no `response` property, it falls back to the `data` property of the error object. This change ensures that the appropriate error message is extracted and displayed, even if the error object structure varies. 
## Type of Change

* [X] Bug fix
* [ ] Feature
* [ ] Other

Fix #5142 

## Screenshots or Videos (if applicable)

https://github.com/user-attachments/assets/b8512348-841a-43b7-9ccb-f796cde58996

### CODE REVIEW

File: libs/designer/src/lib/core/utils/parameters/helper.ts [hunk 1]
```diff
@@ -2284,7 +2284,9 @@ export async function loadDynamicValuesForParameter(
     propertiesToUpdate = { dynamicData: { status: DynamicCallStatus.SUCCEEDED }, editorOptions: { options: dynamicValues } };
   } catch (error: any) {
     const rootMessage = parseErrorMessage(error);
-    const message = error?.response?.data?.error?.message ?? rootMessage;
+    const errorData = error?.response ? error?.response?.data : error?.data;
```
Comment (takyyon) [inline libs/designer/src/lib/core/utils/parameters/helper.ts:2287]: This seems like something which should go into parseErrorMessage function instead?

Comment (takyyon) [reply libs/designer/src/lib/core/utils/parameters/helper.ts:2287]: The two lines should go in here so we don't have to explicitly fix this for all scenarios - libs/logic-apps-shared/src/utils/src/lib/helpers/http.ts
image

**Review by takyyon — APPROVED** [review]

**Review by hartra344 — APPROVED** [review]
