### PR TITLE
fix(designer): Add ignore dirty prop to updateNodeSettings action

### LINKED ISSUE #6206: HTTP trigger logic app with array type as input prompts save without changes
### Describe the Bug with repro steps 

1. Create a new consumption logic app with a HTTP trigger 
2. In the Request Body JSON Schema, define an input property of type "array" 
3. Save and close the Logic App 
4. Click Edit to open the logic app in designer view 
5. Observe the Save button is enabled, prompting for save when no edits have been made 
6. Closing the designer without any editing also then prompts dialog "Your unsaved edits will be discarded." 

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

```json
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "contentVersion": "1.0.0.0",
        "triggers": {
            "manual": {
                "type": "Request",
                "kind": "Http",
                "inputs": {
                    "schema": {
                        "properties": {
                            "p1": {
                                "type": "array"
                            }
                        },
                        "required": [
                            "p1"
                        ],
                        "type": "object"
                    }
                }
            }
        },
        "actions": {
            "Response": {
                "type": "Response",
                "kind": "Http",
                "inputs": {
                    "statusCode": 200,
                    "body": "@triggerBody()"
                },
                "runAfter": {}
            }
        },
        "outputs": {},
        "parameters": {
            "$connections": {
                "type": "Object",
                "defaultValue": {}
            }
        }
    },
    "parameters": {
        "$connections": {
            "value": {}
        }
    }
}
```

### Screenshots or Videos

*No response*

### Browser

Edge

### Additional context

*No response*

### PR DESCRIPTION
**Pull request by ccastrotrejo**
This pull request to `libs/designer/src/lib/core/parsers/ParseReduxAction.ts` includes changes to enhance workflow state management and error logging. The most important changes are the addition of a new action to manage workflow state and improved error logging in the `initializeGraphState` function.

* Added `setIsWorkflowDirty` to the imports from `workflowSlice` to manage the workflow's dirty state.
* Dispatched `setIsWorkflowDirty(false)` in the `initializeGraphState` function to reset the workflow's dirty state upon initialization.
* Enhanced the error logging in the `initializeGraphState` function by including error data in the log trace.

Fixes #6206

### CODE REVIEW

File: libs/designer/src/lib/core/state/operation/operationMetadataSlice.ts [hunk 1]
```diff
@@ -161,6 +161,7 @@ export interface NodeData {
 interface AddSettingsPayload {
   id: string;
   settings: Settings;
+  ignoreDirty: boolean;
```
Comment (rllyy97) [inline libs/designer/src/lib/core/state/operation/operationMetadataSlice.ts:164]: Let's make this optional and default to false, just so we can only use it when we need it

**Review by rllyy97 — APPROVED** [review]
